name: linter-check

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      with:
          node-version: ${{ matrix.node-version }}

      - run: make install
      - name: check linter
      - run: make lint